fix warning about overflow if matiec is running on 64-bit platform, but the generated C code will cross-compiled for 32-bit platform
For example:
./build/config.c:29:39: error: large integer implicitly truncated to unsigned type [-Werror=overflow]
 unsigned long greatest_tick_count__ = 18446744073709551611UL; /*tick*/
                                       ^
compilation terminated due to -Wfatal-errors.
cc1: all warnings being treated as errors