fix compilation error about missing braces
IEC_TIMESPEC has two fields tv_sec and tv_nsec.

Compilation error:
./build/POUS.c:600:45: error: missing braces around initializer [-Werror=missing-braces]
   static const STEP temp_step = {{0, 0}, 0, {0, 0}};
                                             ^
compilation terminated due to -Wfatal-errors.